######################################################################
# Automatically generated by qmake (3.0) Tue Apr 21 07:00:53 2020
######################################################################

TEMPLATE = app
TARGET = Qt_in_90_Sec
INCLUDEPATH += .

# Input
SOURCES += main.cpp
